### ISSUE TITLE
get_access_token is broken >= 1.43.3

### ISSUE THREAD

**Issue by jd** [PyGithub/PyGithub#1023]
Looks like the fix in #1010 only fixed a part of the problem(s) introduced in 1.43.4. With 1.43.5 I get:

```
File "/.tox/test/lib/python3.7/site-packages/github/MainClass.py", line 790, in get_access_token
response_text = response_text.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by webknjaz** [comment]
I just hit the same issue...

**Comment by sfdye** [comment]
Looping in @Hanaasagi

**Comment by Hanaasagi** [comment]
After review #998, I think https://github.com/PyGithub/PyGithub/blob/master/github/MainClass.py#L789 should be removed.
```Python
        if atLeastPython3:
            response_text = response_text.decode('utf-8')
```

Because `httplib.HTTPResponse.read` returns `bytes`, but `requests.models.Response.text` returns `str`(Python3) or `unicode`(Python2) using, and the encoding is determined by HTTP header or `chardet`.

Reference:
- https://github.com/python/cpython/blob/a31f4cc881992e84d351957bd9ac1a92f882fa39/Lib/http/client.py#L457
- https://github.com/kennethreitz/requests/blob/c9309e4c59acfa757b34619205794e18f2009c43/requests/models.py#L861

I will pull request to fix.
