### ISSUE TITLE
Search results limited to 1000 per search query

### ISSUE THREAD

**Issue by malhanpraveen** [PyGithub/PyGithub#1072]
When I use PyGithub to make API calls to GitHub, the max results for a query are only 1000. Is there a way to have pagination or get the total number of results that the Github UI displays?

**Comment by ScottMnemonic** [comment]
This seems to be caused by how the the results of the search are pulled.
A single search can take up the entire allotment of the search rate limit.
Running this:
`
rate = g.get_rate_limit()
print (rate, rate.search, rate.graphql)
res = g.search_users('type:org '+TARGET)
rate = g.get_rate_limit()
print (rate, rate.search, rate.graphql)
`

Results in:
`
RateLimit(core=Rate(remaining=5000, limit=5000)) Rate(remaining=29, limit=30) Rate(remaining=5000, limit=5000)
Verizon Media
RateLimit(core=Rate(remaining=5000, limit=5000)) Rate(remaining=1, limit=30) Rate(remaining=5000, limit=5000)
`

**Comment by wangpeipei90** [comment]
I am also looking for a solution to this limitation. From the GitHub API, it says "Just like searching on Google, you sometimes want to see a few pages of search results so that you can find the item that best meets your needs. **To satisfy that need, the GitHub Search API provides up to 1,000 results for each search.**".   
The GitHub UI displays the same number, too.
I would be very glad if anyone can provide a solution.

**Comment by dantonrodriguez** [comment]
+1 to what is said above, the actual value that is desired is being discarded.
 @wangpeipei90:
For a work around, you can use the `_PaginatedList__requester..requestJsonAndCheck()` method which returns a tuple: (headers, data). If this tuple is `r`, then `r[1][total_count]` will give you what you want.

**Comment by wangpeipei90** [comment]
@dantonrodriguez 
From my understanding of [PaginatedList,](https://github.com/PyGithub/PyGithub/blob/master/github/PaginatedList.py)  "data['total_count']" returns the total number of records, but not all results. That is to say, you know that you have over 1000 records but can only retrieve the first 1000. 
Correct me if I am wrong.

**Comment by dantonrodriguez** [comment]
@wangpeipei90: yes, I believe you're correct. I misunderstood your goal, sorry.

**Comment by ScottMnemonic** [comment]
> @dantonrodriguez
> From my understanding of [PaginatedList,](https://github.com/PyGithub/PyGithub/blob/master/github/PaginatedList.py) "data['total_count']" returns the total number of records, but not all results. That is to say, you know that you have over 1000 records but can only retrieve the first 1000.
> Correct me if I am wrong.

That should be correct, however there is still a problem here.

See my example.

A single call to the search returns the 1000 results as expected, but uses *29* search calls to the API.

For 29 search API calls I should be getting 29,000 results.


As it is, it was easier to implement my own search functionality with _requests_ as a solution to the issue.
