### ISSUE TITLE
Custom Port Number in API URL

### ISSUE THREAD

**Issue by Jie-Yang** [PyGithub/PyGithub#1078]
Hi All,
I am trying to use this to connect to a enterprise Github exposed at a port different than 443. 
For example, when I try this URL below, I get errors. It seems there is a port checking in the code, and only accept 443 by default. And there is no way to change it? Is there a way to use custom port in the API url? Thanks. 

**Example URL**
"https://github.company.com:3690/api/v3"
**Errors:**
 File "/var/task/github/Requester.py", line 440, in __makeAbsoluteUrl
    assert o.port == self.__port
AssertionError

**Comment by Jie-Yang** [comment]
Or, may I ask what is the reason behind the port check here?
assert o.port == self.__port
thanks.

**Comment by sfdye** [comment]
How did you initialize the Github object? It should work like this:
`g = Github(base_url="https://github.company.com:3690/api/v3", login_or_token="token")`

**Comment by Jie-Yang** [comment]
Hi sfdye,

Thanks for the help. Yes that is the way I use. Once I comment out that assert line code, it start to work.

**Comment by atorrescogollo** [comment]
This issue seems not to be fixed.

Here, there is an assertion that forces the requested port to be equals to the base_url port:
https://github.com/PyGithub/PyGithub/blob/babcbcd04fd5605634855f621b8558afc5cbc515/github/Requester.py#L590-L598

`urllib.parse.urlparse` only returns port when explicitly set:
```python
>>> import urllib.parse
>>> urllib.parse.urlparse("https://example.com:443").port
443
>>> urllib.parse.urlparse("https://example.com").port == None
True
```

It should not be a problem, but all the URLs for the API are only taking the URL into account so the most of the times the assertion is `None == None`. For example:
https://github.com/PyGithub/PyGithub/blob/babcbcd04fd5605634855f621b8558afc5cbc515/github/Organization.py#L578-L580

On the other hand, [`Requester.__createConnection`](https://github.com/PyGithub/PyGithub/blob/babcbcd04fd5605634855f621b8558afc5cbc515/github/Requester.py#L610-L626) already creates the connectionClass so, why not use relative paths exclusively for all `requestJsonAndCheck` calls? This is already done for some requests:
https://github.com/PyGithub/PyGithub/blob/babcbcd04fd5605634855f621b8558afc5cbc515/github/Organization.py#L922-L924
