### ISSUE TITLE
Move tests/ back into github/tests and ship within tarball, or at least provide github.testing?

### ISSUE THREAD

**Issue by yarikoptic** [PyGithub/PyGithub#1098]
#1031 recently placed `tests/` outside of the `github` package. The main reasoning, if I got it right from #672, is the size -- tests indeed add up to the distribution.  I personally from time to time  do run tests of the package I am "questioning", which cannot be done if no `tests/` shipped.  To my knowledge, many (if not most) packages do ship `tests` subpackages as part of their packages. 
Moreover, my use case is actually to consider using `github.tests.Framework`  in our ([datalad](http://datalad.org)) tests to verify correct operation of our code which makes use of the `github` package.   I am not sure if that might be advised against, but now I wouldn't even be able to do so since there is no installed `github.tests` module.  If you see `Framework` to be potentially reused by 3rd party packages like ours, and if you insist that no `tests/` shipped as part of the `github` package, may be it makes sense then to move `Framework` components to e.g. `github.testing` (analogous to `numpy.testing` etc)?

**Comment by lmazuel** [comment]
I have exactly the same problem, I'm importing the Framework and this update broke my CI :(
![image](https://user-images.githubusercontent.com/1050156/57477678-13feec00-724e-11e9-99ff-6ac29fbe4a89.png)

I have using your class which was part of the public API of the package to record my own high level tests, and now I have to pin the PyGithub version until I have time to replace it with something else (vcrpy?)

I understand if you don't want to go back to your decision, but at least I wanted to point the impact: since this naming was public (no underscore), it becomes automatically part of the public API and changing it is a breaking change that should required a major version bump (and not a patch version :()

**Comment by mgorny** [comment]
Now that tests are not part of build directory and require 2to3, it's painful to use the same checkout to test both py2 and py3.

**Comment by yarikoptic** [comment]
Just to keep @stale fresh ;-)

**Comment by s-t-e-v-e-n-k** [comment]
The most recent changes no longer require 2to3, so I'm going to close this since it should now be possible to test py2 and py3 in the same checkout.

**Comment by sandrotosi** [comment]
@s-t-e-v-e-n-k but now sadly MANIFEST.in is not updated to include `tests/` in the released tarball, so distributions wont have tests anymore :( can you take care of that? thanks!
