### ISSUE TITLE
Mock for testing

### ISSUE THREAD

**Issue by ahmad88me** [PyGithub/PyGithub#1127]
Is there a way to fake GitHub APIs like some kind of a mock? 
something like 
```
g = Github(fake=True)
repo = g.get_repo('non-existing/repo', default={'name': 'repo', ...})
```

**Comment by nuarhu** [comment]
Any information on this? Or maybe a bit more inline documentation in the test classes could already help to decide whether they can be used for such tests.

**Comment by ahmad88me** [comment]
@nuarhu actually the test cases use the actual github APIs. This mock suggestions wouldn't call GitHub APIs.

**Comment by steveoh** [comment]
It would be great to be able to test using some classes without calling actual api's. I'm trying to create a new issue and it is not very intuitive.

**Comment by ChaiBapchya** [comment]
@ahmad88me did you get a workaround for mocking Github APIs? I scoured the internet but to no avail.

**Comment by ahmad88me** [comment]
@ChaiBapchya I didn't get around it yet. I will try to do so soon.

**Comment by ChaiBapchya** [comment]
Sure thanks. @ahmad88me any update or any pointers?

**Comment by ahmad88me** [comment]
@ChaiBapchya  
@steveoh 
@nuarhu 

If you are still interested in the mock option, I've created this pull request.

https://github.com/PyGithub/PyGithub/pull/1720

**Comment by kwk** [comment]
Hello. I'm very interested in this for many reasons:

* I want to run tests without having access to github, e.g. when working offline.
* I want to be able to create "golden files". That is a mode where you actually call the real Github API and store the results for later use in tests. This is helpful in case the API changes.
* I don't want to pass along credentials just to run tests on github.

In order to deal with some of the shortcomings of changing API responses, changing UUIDs and time values I've once created a library one can use in the Go programming language: https://github.com/kwk/golden . Some of the ideas I use to this day also in Python. For example the on-the-fly updating of golden files I use [here](https://github.com/fedora-llvm-team/llvm-snapshots/blob/5d8b9af3b0f7e861678ef7825390c44eb2afde23/snapshot_manager/tests/build_status_test.py#L24-L29). This allows me to set the `write_golden_file` argument of the [`get_cause_from_build_log`](https://github.com/fedora-llvm-team/llvm-snapshots/blob/5d8b9af3b0f7e861678ef7825390c44eb2afde23/snapshot_manager/snapshot_manager/build_status.py#L233-L258) function to `True` and have the golden file written that contains the expected output that I want to use [here](https://github.com/fedora-llvm-team/llvm-snapshots/blob/5d8b9af3b0f7e861678ef7825390c44eb2afde23/snapshot_manager/tests/build_status_test.py#L32-L35) where I read the file back in. Of course, you need to run the test twice, one time when you write the golden files and the next time when you just consume the file.
