### ISSUE TITLE
AuthUser lazy login field initialization and equality issue

### ISSUE THREAD

**Issue by DragosDumitrache** [PyGithub/PyGithub#1180]
Hello,

I'm raising another issue as even though the fix is potentially quite straightforward, I can't seem to get the project building locally, due to various reasons.

Noticed it briefly yesterday, but if I obtain the authenticated user and print it as in the example bellow, the representation has no login information. However, if I manually print the login value, I will get the expected result.

```py
>>> auth_user = git.get_user()
>>> print(auth_user)
AuthenticatedUser(login=None)

>> print(auth_user.login)
dragosdumitrache
```

I suspect the issue might be because the `__repr__` method on `AuthenticatedUser` directly references the login value: `self._login.value`, instead of using the property `login()`. However, this is just a guess on my end, since I couldn't run the code locally.

Regarding local development, I am using Python 3.7.3, and the project only seems compatible with python2, is that correct? I'm asking so that in the future I can be more useful than just raising issues :)

L.E: Seems to print the correct representation if I manually check the `login` value and then print the entire object.
```py
>>> print(auth_user.login)
dragosdumitrache
>>> print(auth_user)
AuthenticatedUser(login=dragosdumitrache)
```

Furthermore, as it relates to `AuthenticatedUser`, is there a reason why `AuthenticatedUser` would not be equal to the equivalent `NamedUser`? There's no hash implementation

**Comment by s-t-e-v-e-n-k** [comment]
This is actually on purpose. From github/MainClass

```
        if login is github.GithubObject.NotSet:
            return AuthenticatedUser.AuthenticatedUser(self.__requester, {}, {"url": "/user"}, completed=False)
```

Which means self._login will be NotSet because it's a lazy object, and if __repr__ used self.login, it would round-trip out to github.

Furthermore, I should have landed code today that makes your experience on Python 3.7 much better.

And NamedUser and AuthenicatedUser implement different methods, methods that anyone can call for any Github user versus methods you can only call for the user you are logged in as.
