### ISSUE TITLE
Expose adding custom headers

### ISSUE THREAD

**Issue by aaomidi** [PyGithub/PyGithub#1314]
I want to add a timezone header to the requests going out of PyGithub so GitHub returns datetime values with the correct timezone. I don't see a way to modifying or extending the headers being sent to github.

https://developer.github.com/v3/#using-the-time-zone-header

**Comment by s-t-e-v-e-n-k** [comment]
The monkey patch way would be to override Requester.__requestEncode() to set requestHeaders to a dict including the Time-Zone in the right format, and then call the original method.

The correct way requires more thought, since I can't see a cross platform way of getting the current timzone in an Oslon format inside Python without a third party module.
