### ISSUE TITLE
cannot create a correct release from tag when using create_git_tag_and_release

### ISSUE THREAD

**Issue by leihu0724** [PyGithub/PyGithub#1336]
There is an issue when using create_git_tag_and_release function to create a release in Repository.py.

`   def create_git_tag_and_release(
        self,
        tag,
        tag_message,
        release_name,
        release_message,
        object,
        type,
        tagger=github.GithubObject.NotSet,
        draft=False,
        prerelease=False,
    ):
        self.create_git_tag(tag, tag_message, object, type, tagger)
        return self.create_git_release(
            tag, release_name, release_message, draft, prerelease
        )`

The code cannot create a correct commit id from the created tag. please help to fix it. thanks.

**Comment by s-t-e-v-e-n-k** [comment]
So let's break it down further. Since Repository.create_git_tag_and_release() fails to create a tag pointing to the correct commit, does Repository.create_git_tag() also show the same behaviour? Do you have an example you can show us?

**Comment by leihu0724** [comment]
Repository.create_git_tag()  works fine, instead I use the Repository.create_git_release() which can can create both a correct release and tag for me with a correct commit id. 

From the source code, I found there is no passing a parameter pointing to the commit info:
        return self.create_git_release(tag, release_name, release_message, draft, prerelease)
it should provide target_commitish parameter.

Not sure my idea is correct.

**Comment by s-t-e-v-e-n-k** [comment]
It's a good theory, worth checking out. Thanks for your explanation, that helps me work out what is going on. I'll investigate this based on your information.

**Comment by diverru** [comment]
+1, noticed following:
`create_git_tag_and_release(tag="v1.2", object="commit_sha", ...)`
Expected behaviour:
  1) created tag with name "v1.2"
  2) this tag points to commit "commit_sha"
  3) created release associated with tag "v1.2"
Real behaviour
  1) tag is probably created via `create_git_tag`, but
  2) tag IS NOT referencing commit "commit_sha"
  3) `create_git_release` creates another tag pointing to another (wrong) commit

Did following to fix behaviour:
  1) manually creating tag via `tag = create_git_tag(object=commit_sha, ...)`
  2) manually creating reference to the tag via `create_git_ref("refs/tags/v1.2", tag.sha)`
  3) making release via `create_git_release(tag.tag, ...)`

**Comment by diverru** [comment]
`target_commitish` probably will fix the issue

**Comment by s-t-e-v-e-n-k** [comment]
At least based on the code, the tag should reference the correct sha, since the object parameter is passed into create_git_tag() ...

**Comment by diverru** [comment]
yep, created tag is pointing to the correct revision, but the problem is that for some reason `create_git_tag` doesn't creates reference (`refs/tags/...`) to the tag object sha and `create_git_release` ignores passed tag and creates new with the same name and according to the API that tag is pointing to the head of the default repository branch (in our case it is latest commit in the `develop` branch)

**Comment by s-t-e-v-e-n-k** [comment]
From https://developer.github.com/v3/git/tags/:

Note that creating a tag object does not create the reference that makes a tag in Git. If you want to create an annotated tag in Git, you have to do this call to create the tag object, and then create the refs/tags/[tag] reference.


Please don't conflate this bug with a different (and documented upstream!) issue.

**Comment by diverru** [comment]
OK, haven't read docs till the end.
Was a little bit confused with the sentence "The Git tags API only supports annotated tag objects, not lightweight tags."
But in fact in order to fix subject behaviour you need do one of the following (though i'm not sure, it's subject to test):
1) don't call `create_git_tag` and call `create_git_release` with `tag="tag_name", target_commitish="commit sha"`
2) call `create_git_tag`, create reference, call `create_git_release` as expected
3) call `create_git_tag`, call `create_git_release` with `tag=tag.name` and `target_commitish=tag.sha`
