### ISSUE TITLE
Remove assert statements in favor of static type checking

### ISSUE THREAD

**Issue by sfdye** [PyGithub/PyGithub#1483]
The `assert` statements are duplicates, especially for types, since we have static type checking now. 

Removing them to gain some speed 😄

**Comment by sfdye** [comment]
@s-t-e-v-e-n-k this one too

**Comment by s-t-e-v-e-n-k** [comment]
Do we have static type checking? I'd argue we don't since the asserts are run time, and mypy checking happens at check in. I suspect we'd need to move the annotations into the .py files and lose the .pyi files -- however, in general I approve of the idea if we don't lose the safety that the asserts gives us at run time.

**Comment by sfdye** [comment]
Yes we have, only not 100%. (I am working on this)

The `pyi` type stub is less intrusive and easier for community contribution. It works the same as inline type hint. 

Because we don't expect the type to change during runtime (if they do, it's a serious problem), all the asserts statements (for type) are basically the same as static type hints.
