### ISSUE TITLE
Repository.topics does not match Repository.get_topics()

### ISSUE THREAD

**Issue by markediez** [PyGithub/PyGithub#1504]
For a repository with topics, `Repository.topics` is returning `None` whereas `Repository.get_topics()` properly returns a list of string (my topics). The latter is correct.

This occurred for a private org repo.

```
Python Version: 3.7.4
      PyGithub: 1.51
```

**Comment by s-t-e-v-e-n-k** [comment]
I suspect topics is no longer populated because it isn't being sent by GitHub. I'll push up a PR to remove it.

**Comment by ebickle** [comment]
Just a heads up that this change looks like it was made in error.

`https://api.github.com/orgs/org-name/repos` is properly returning `topics` in the JSON response and is documented at https://docs.github.com/en/rest/reference/repos

Removing the topics from the Repository entry creates unnecessary load - previously topics could be processed in "bulk" without any additional API requests; now it's an O(n) operation that scales with the number of repositories.

I'm debating submitting a new Pull Request, but wanted to check in first. Would it be better to restore the old behavior of loading the topics if they exist from the payload, but add some intelligence to `Repository.get_topics()` so that it falls back to making the request if the 'stored' topics is `None`?
