### ISSUE TITLE
Inconsistent data type for time related attributes of `<class 'github.Issue.Issue'>`

### ISSUE THREAD

**Issue by FYJen** [PyGithub/PyGithub#1568]
When I constructed an `Issue` object, I was expecting time-related fields (eg: `created_at` and `closed_at`) would return the same data type: `datetime.datetime`. However, `last_modified` did not. It returned in a string format representing date and time, like the following:
```
ipdb> issue.last_modified
'Sat, 20 Jun 2020 00:43:01 GMT'
```

It is not a blocker as there are workarounds. But it would be a better experience if the data type is consistent for those fields.

**Comment by s-t-e-v-e-n-k** [comment]
Duplicate of #512

**Comment by s-t-e-v-e-n-k** [comment]
Actually, no it isn't, my bad.

**Comment by s-t-e-v-e-n-k** [comment]
The reasons are from an implementation detail -- ``created_at`` and ``closed_at`` are attributes on Issue, ``last_modified`` comes from the superclass, and is passed as-is to further requests if it's set. We should probably move it to a _ attribute. Since it's useful, we can then a real last_modified that is datetime.datetime.
