### ISSUE TITLE
allow PyJWT 2+

### ISSUE THREAD

**Issue by valentijnscholten** [PyGithub/PyGithub#1832]
other libraries are moving to PyJWT2+ as requirement, is it possible to update pygithub as well? currently we can't use for example pygithub together with django-social-core

**Comment by s-t-e-v-e-n-k** [comment]
It's on my list, just a lack of free time to tackle it. :-(

**Comment by fabaff** [comment]
I'm looking forward to see. The NixOS package will break if we update `PyJWT`.

**Comment by fabaff** [comment]
Any progress?

It's blocking the PyJWT package update on NixOS. I guess that it affecting other distributions as well.

**Comment by samamorgan** [comment]
What breaking changes does PyJWT>2 introduce?

**Comment by s-t-e-v-e-n-k** [comment]
https://github.com/PyGithub/PyGithub/issues/1796 is what caused me to pin it, I just haven't time to dig into it

**Comment by samamorgan** [comment]
@s-t-e-v-e-n-k the issues mentioned there are related to Python 3.5 specifically. I'm assuming these syntax errors occur due to syntax changes with Python 3.6. Which makes sense considering the drop of Python 3.5 support.

Isn't the current version of PyGithub dropping Python 3.5 support as well? That was mentioned in the latest release.

**Comment by s-t-e-v-e-n-k** [comment]
The current version has dropped support for 3.5, yes. I'll propose a PR to drop the pin soon.
