### ISSUE TITLE
repo.get_stargazers().totalCount does not return a value higher than 40000

### ISSUE THREAD

**Issue by timkofu** [PyGithub/PyGithub#1876]
Hi,

A strange issue here; I've tested it with several repos that I've starred that have over 40000 stars. Repos with less stars than this have the correct value returned. Reproduction code:

```python
In [37]: from github import Github; import os

In [38]: ghh = Github(login_or_token=os.getenv("GH_AUTH_TOKEN"))

In [39]: user = ghh.get_user()

In [40]: stared = user.get_starred()

In [41]: page4 = stared.get_page(4)

In [42]: test_project = page4[27]   # any repo that has over 40k stars

In [43]: test_project.name
Out[43]: 'flask'

In [44]: test_project.get_stargazers().totalCount
Out[44]: 40000

```

My access token has only the `public_repo` permission.

**Comment by s-t-e-v-e-n-k** [comment]
All we can do in this case is present the data GitHub returns -- `get_stargazers()` returns a PaginatedList so you can enumerate that, and I suspect those have some upper limits enforced by GitHub. There is a `stargazers_count` property if you're only concerned with the number and not the details.

**Comment by glenn-jocher** [comment]
@timkofu @s-t-e-v-e-n-k any ideas?  Reason I'm asking is because I've made https://github.com/ultralytics/stars for counting stars over a trailing time period, i.e. last 30 days, to compare AI repo trends, but am unable to include larger repos like sklearn and transformers that also belong on the list:

<img width="1420" alt="Screenshot 2022-03-31 at 23 35 49" src="https://user-images.githubusercontent.com/26833433/161434007-ba88e531-7532-497d-8be3-4f2878584385.png">
