### ISSUE TITLE
 Failed to establish a new connection: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by BalveerSinghYT** [PyGithub/PyGithub#2093]
Hi team, 

I'm getting this error, not able to resolve it.

`HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/XXXX/XXXXX (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcf030252e8>: Failed to establish a new connection: [Errno 111] Connection refused',)) `

I'm fetching branch names from some repository with help of PyGithub. Everything is working when I run my web app with Gunicorn or by using the default Django webserver. But in production, it's not working & I'm getting the error mentioned above.

**Comment by BalveerSinghYT** [comment]
The error didn't resolve yet. Can you share some reference links regarding this?

**Comment by EnricoMi** [comment]
This is likely due to missing proxy settings: #2426 or other network restrictions in your production environment.

If network is fine, you can configure retries via the `retry` argument:

```python
gh = Github(retry=10)
```

You can configure more complex retry logic as follows:

```python
from urllib3.util import Retry

gh = Github(retry=Retry(10))
```

See https://urllib3.readthedocs.io/en/stable/reference/urllib3.util.html#urllib3.util.Retry for all available options.
