### ISSUE TITLE
Max retries exceeded with url

### ISSUE THREAD

**Issue by sharathsridhar** [PyGithub/PyGithub#2511]
Hello,

When running the below code,
```
from github import Github

g = Github(githubToken) #ghp_xxxxx
repo = g.get_repo(githubRepo)
query = repo.get_contents(cfg.Github["QueryPath"], cfg.Github["Branch"])
self.testQuery = encodedOnboardingQuery.decoded_content.decode("utf-8")
```
I run into this error

`Type: <class 'requests.exceptions.ConnectTimeout'>, Value: HTTPSConnectionPool(host='[api.github.com](http://api.github.com/)', port=443): Max retries exceeded with url: /repos/abcd/xxxx (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f75390c04d0>, 'Connection to [api.github.com](http://api.github.com/) timed out. (connect timeout=15)')).`

1. Is this a rate limit issue or something else?
2. If I need to add retry logic, how do I do that

Thank You.

**Comment by EnricoMi** [comment]
This issue is unrelated to rate limits as the connection cannot be established in the first place. Github servers seem to be too busy.

You an configure retries via the `retry` argument:

```python
g = Github(githubToken, retry=10)
```

You can configure more complex retry logic as follows:

```python
from urllib3.util import Retry

g = Github(githubToken, retry=Retry(10))
```

See https://urllib3.readthedocs.io/en/stable/reference/urllib3.util.html#urllib3.util.Retry for all available options.

**Comment by sharathsridhar** [comment]
Got it. I will try this. Thank you @EnricoMi
