### ISSUE TITLE
Implement (de)serialization save/load

### ISSUE THREAD

**Issue by jacquev6** [PyGithub/PyGithub#258]

**Comment by jzelinskie** [comment]
v2 is dead

**Comment by bilderbuchi** [comment]
@jzelinskie are you saying this feature is in master already? because, this being milestoned for a 2.0 which will come or not is orthogonal/unconnected to the subject of the issue...

**Comment by jzelinskie** [comment]
@bilderbuchi unless I am also confused, "v2" was a branch that contained a complete rewrite that was abandoned recently. It already had some releases, but has been discontinued. I don't know if these issues are for the master branch or for that removed branch.

**Comment by bilderbuchi** [comment]
The way I understood it, this was a feature intended to land in the v2 branch for development of 2.0 (the version). The issues, in general, are for the master/release branch. That's where the v2 branch would have ended up, eventually, too. The v2 branch being dead does not mean this issue is irrelevant (Afaik).

**Comment by jzelinskie** [comment]
I'll leave this open for master than. Thanks for easing some confusion.
