### ISSUE TITLE
How to construct object from context.payload.pull_request?

### ISSUE THREAD

**Issue by Kamilcuk** [PyGithub/PyGithub#2910]
In the context of github actions, the context.payload is available with github objects. How can I construct `github.PullRequest.PullRequest` object from context.payload.pull_request data?

I tried:

```
gh = github.Github(auth=github.Auth.Token(os.environ["GITHUB_TOKEN"]))
github.PullRequest.PullRequest(gh, {}, context.payload.pull_request, False)
```

However, the `gh` as the first argumnet is not right. How to fix it?

Thanks.

**Comment by xvega** [comment]
Hello @Kamilcuk 

I'm not a maintainer but am looking into issues to contribute solutions. Seeing many "how to fix my code" questions can be a bit challenging when we're trying to identify bugs or feature requests that need attention. For how-to and usage questions about PyGithub, or when seeking ideas or help with your code, the [PyGitHub Discussions Q&A section](https://github.com/PyGithub/PyGithub/discussions/categories/q-a) is the perfect spot. It's set up specifically for asking the community for help

For a broader audience and potentially quicker responses, you might also consider posting your question on Stack Overflow with the pygithub tag.

GitHub Issues is ideally for reporting bugs or making feature requests. This distinction helps focus on improving and maintaining the library, especially since PyGithub is on the lookout for new maintainers.

**Comment by Kamilcuk** [comment]
Great, ok!
