### ISSUE TITLE
Maintain PyGithub - looking for volunteers

### ISSUE THREAD

**Issue by jacquev6** [PyGithub/PyGithub#297]
Hello everyone,

I've obviously neglected PyGithub in the last few months and my current priorities are hardly compatible with doing a good job on PyGithub.

I'm looking for volunteer(s) to take over PyGithub. I would transfer ownership of the main PyGithub repository to a GitHub organization, and give admin permissions on the PyPI package as well.

Please comment on this issue if you're interested.

**Comment by nhomar** [comment]
You can count on us.
We use a lot your library and I was facing some little issues which can help to move forward faster this cool and well done library.

Our organization is @vauxoo you can look for our opensource work here in github.

Regards.

**Comment by jzelinskie** [comment]
I wouldn't mind helping out, but I wouldn't want to be the sole maintainer. We're dependent on this library at CoreOS (specifically for Quay.io).

**Comment by thiderman** [comment]
I don't think I can actually help out because of the same reasons, but big kudos for taking this step and making sure that your project lives on! :+1:

**Comment by jacquev6** [comment]
Thanks for your replies!

@nhomar @jzelinskie I've transferred the repository to @PyGithub and I've invited you to @PyGithub/members team. If you give me your PyPI user names, I'll give you permissions to upload new versions of https://pypi.python.org/pypi/PyGithub.

Let me know if you have any question or if something doesn't work as expected.

@thiderman Thanks for the kudos.

**Comment by nhomar** [comment]
Hello @jacquev6 

My PyPi user is nhomar as well.

Thanks, let's put in our roadmap improve and finish all what we can... 

Just FYI. We are integrating odoo with git-flow and we planned use your lib, now let's put hand in work...

regards.

**Comment by jzelinskie** [comment]
I'm jzelinskie @ pypi. Thanks again for the effort!

**Comment by jacquev6** [comment]
You now both have the "Maintainer" role on PyPI; this should allow you to publish new versions of the package.

Thank *you* for taking over ! I'll try to be responsive if you have questions during this transition phase.

**Comment by nhomar** [comment]
@jzelinskie @jacquev6 

Hello all.

I really appreciate if you extend a little the sources of the methodology and some minimal rules to avoid misunderstandings in the way we develop.

For example:

I see you use git-flow to manage names of repositories, but I can not see the plans of things already achieve in develop branch, which is tthe difference between one and another (master and develop).

I prefer personally have a branch per version that can be backported but I see we are marking versions using deploy version method using pypi strategy, can we change that? can you tell us an strategy/methodology which you are using in order to follow your lead.

The objective is follow an unique strategy in order to manage correctly everything and be sure we can follow the work of @jzelinskie and they can follow our work also.

The example before was only an example but there are many areas where we can document the "how to push the work".

Regards.

**Comment by jzelinskie** [comment]
This sounds really good. I think we got ahead of ourselves by merging things right away. It would be nice if we had an established practice. I'm also always available on as jzelinskie on freenode IRC. Maybe we should make a channel?

**Comment by nhomar** [comment]
I don't use IRC too much :-) I prefer normal lists/issues and for chat maybe some hangouts and google-hangout for chats (always I compromise go to IRC I fail in a huge way).

nhomar at gmail is a valid gmail account for that.

**Comment by jzelinskie** [comment]
What are the differences between the 2.x and 1.x releases?

**Comment by syndbg** [comment]
I would like to help out! We can have a chat or something to see if our goals/expectations align.

Also, writing a contribution guide and trying to pipeline the development process of PyGithub, is imo the first thing to do during the transition.

**Comment by jacquev6** [comment]
@jzelinskie  2.x was an attempt to rewrite PyGithub from scratch based on my experience with 1.x.

I think this is not worth maintaining. It's never been published on PyPI, only a few tags in a separate branch in the repository, so people using it were really only experimenting.

**Comment by jhermann** [comment]
I might contribute a few PRs while working on https://github.com/jhermann/gh-commander

**Comment by justinclift** [comment]
Has new maintainer-ship for this been sorted out?

If so, the README should probably be updated + this issue closed. :wink:

**Comment by skyl** [comment]
I wouldn't mind having the rights to close issues or whatnot. Like https://github.com/PyGithub/PyGithub/issues/302 .. and maybe this one.

**Comment by jzelinskie** [comment]
I think we still need people to have access to readthedocs. I've never used it before so, yeah...

**Comment by justinclift** [comment]
Asking if maintainer-ship for this has been sorted out, because it's been requested back in February and there's no clear answer.  We skipped using PyGitHub due to this, and went with githubpy instead (which has worked well enough so far).

Just pointing it out. :wink:

**Comment by hintjens** [comment]
@jacquev6 I'm a happy user of PyGithub, and for what it's worth we solved the maintainer crisis in our ZeroMQ projects by using a better process (C4, http://rfc.zeromq.org/spec:22).

**Comment by jzelinskie** [comment]
@hintjens C4 already looks extremely similar to how the project is being currently ran.

**Comment by hintjens** [comment]
@jzelinskie perhaps, I don't see the process for the project documented anywhere. The key things about C4 are that we merge pull requests rapidly, and do core review asynchronously afterwards, ideally via more patches rather than discussion. We assume every patch is good unless the contributor is known to be a bad actor in which case we ban them. Pull requests do not stay open for more than a few minutes or hours (once maintainers are awake).

Backing this, we do a lot of CI to ensure patches don't break existing apps.

**Comment by jayfk** [comment]
I'd be happy to help out here. My username on pypi is the same as on GitHub.

**Comment by ahmad88me** [comment]
I might be able to help out as well, I have a project depending heavily on this awesome lib.

**Comment by jayfk** [comment]
🔔  @jacquev6 @jzelinskie I'm still here to help :)

**Comment by sfdye** [comment]
@jacquev6 @jzelinskie I am too. Taking over rtd and it’s working now just need to be invited to the PyGithub members team so I can manage the repo webhooks.

**Comment by sfdye** [comment]
Thanks @jzelinskie for the invitation. I've taking over readthedocs for now and have set up webhooks to build each master commits.
