### ISSUE TITLE
No exception raised on hitting rate limit

### ISSUE THREAD

**Issue by Morg42** [PyGithub/PyGithub#3080]
Hi, 

maybe I'm doing something wrong, but I couldn't find a setting for disabling/enabling rate limit exceptions...?

When accessing Github hitting a rate limit or while a rate limit is active, I don't get a GithubException.RateLimitExceededException or any Exception, only a printed (?) output mentioning the rate limit:

```
>>> from github import Github
>>> g = Github()
>>> g.get_repo('PyGithub/PyGithub')
Request GET /repos/smarthomeNG/plugins failed with 403: rate limit exceeded
Setting next backoff to 855.664145s
```

In interactive console, the command doesn't return, but waits for the backoff time to end.
Using it in an application, I get INFO log entries from github.GithubRetry, but no waiting.

I'd expect it to throw an Exception (RateLimitExceededException), so I can programmatically work on it.

Is this my fault (possibly for not finding the correct settings) or something to investigate further?

I'm using PyGithub 2.4.0 installed via pip3 on python 3.10.9.

**Comment by EnricoMi** [comment]
There is no immediate exception because the issue (rate limit) is retry-able and Github provided a time to wait before sending the next request (here 855s). The default behaviour is to comply and wait.

If you want no retry at all, set `retry=None` when creating your `Github` instance. Or use a `urllib3.util.Retry` instance.

**Comment by Morg42** [comment]
Oh, so I didn't realize retry prohibits rate limit exceptions...

Thanks, solved for me.
