### ISSUE TITLE
Documentation link

### ISSUE THREAD

**Issue by OrkoHunter** [PyGithub/PyGithub#509]
Hello,

I was unable to find the link for the documentation of the library. I cloned it and built the doc myself. It would be great to have the docs configured over `readthedocs.io`.

**Comment by jidicula** [comment]
I've been using http://pygithub.readthedocs.org/en/stable, which is linked in the README in this button: 
![screen shot 2016-12-27 at 6 05 30 pm](https://cloud.githubusercontent.com/assets/12765385/21510242/26839cf0-cc5f-11e6-9a20-08f99a2d4f20.png)

I'm not sure whether it's updated though, because it seems to be missing the "update_file" function. Can you link to your clone of the docs?

**Comment by OrkoHunter** [comment]
I'm sorry, I didn't look in the badges. :)
I still wish to have a section of documentation in the Readme.

**Comment by jidicula** [comment]
> I still wish to have a section of documentation in the Readme.

I would too :)
