### ISSUE TITLE
Remove Python 2.6 support?

### ISSUE THREAD

**Issue by jayfk** [PyGithub/PyGithub#592]
We are still testing against Python 2.6: any objections to remove formal support for it?

**Comment by hugovk** [comment]
Drop it and 3.2 as well. Consider dropping 3.3 at the same time, all are EOL. Dropping 3.2 will help get of the strange Unicode handling it requires.

## Reasons for dropping old ones

* https://en.wikipedia.org/wiki/CPython#Version_history

### 2.6

* Unsupported since [2013-10-29](https://en.wikipedia.org/wiki/CPython#Version_history)
* https://snarky.ca/stop-using-python-2-6/
* http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html
* http://www.python3statement.org
* Current pip 9 deprecates Python 2.6 support, pip 10 won't support it (https://github.com/pypa/pip/issues/3955)
* Not much PyPI traffic (June 2016) https://github.com/pypa/pip/issues/3796

### 3.2

* Unsupported since [2016-02-27](https://en.wikipedia.org/wiki/CPython#Version_history)
* pip 8 no longer supports Python 3.2 ([link](https://pip.pypa.io/en/stable/news/))
* Coverage 4 no longer supports Python 3.2 ([link](https://bitbucket.org/ned/coveragepy/issues/407/coverage-failing-on-python-325-using))
* Requests no longer supports Python 3.2
* Virtually no PyPI traffic (June 2016) https://github.com/pypa/pip/issues/3796

### 3.3

* Unsupported since [2017-09-29](https://en.wikipedia.org/wiki/CPython#Version_history)
* pip 10 will deprecate Python 3.3 support, pip 11 won't support it (https://github.com/pypa/pip/issues/3796)
* Very little PyPI traffic (June 2016) https://github.com/pypa/pip/issues/3796

**Comment by hugovk** [comment]
Please see PR https://github.com/PyGithub/PyGithub/pull/674.
