### ISSUE TITLE
Don't include tests in distribution?

### ISSUE THREAD

**Issue by asottile** [PyGithub/PyGithub#672]
One task I'm working on is sliming down a docker image and one thing that came up was `pygithub`.

The library itself is tiny, but we take a *huge* hit from the tests

```console
# du -hs lib/python3.6/site-packages/github/
21M	lib/python3.6/site-packages/github/
# du -hs lib/python3.6/site-packages/github/tests
20M	lib/python3.6/site-packages/github/tests
# rm -rf lib/python3.6/site-packages/github/tests && du -hs lib/python3.6/site-packages/github/
1.3M	lib/python3.6/site-packages/github/
```

Would a PR which doesn't include the tests in the distribution by default be acceptable?

**Comment by jasonwhite** [comment]
It looks like the tests were intentionally added back in 2012 to the pypi tarball by commit c6609fd4dacf7347125fdf3d4cf4ac1afeef7d4d for #86.

I don't know if the tests are still needed in the pypi distribution or not. It could be a historical artifact -- I don't think travis-ci was around back then. It seems silly to include them when they get run by the CI build for every commit.

I would feel more comfortable taking a PR for this if another maintainer could confirm they are not needed.

**Comment by lmazuel** [comment]
I personally uses your `github.tests.Framework` to record my own tooling that uses PyGithub. Since the way PyGithub is designed, it's incompatible with VCRPy:
https://github.com/kevin1024/vcrpy/issues/227

So I understand removing the tests themself and the recordings, but I feel like the Framework at least should still shipped to enable this scenario.

My two cents,

**Comment by sfdye** [comment]
@lmazuel Thanks for your input. I don't have much experience with vcr, do you think now that we are using requests, it's feasible to migrate the whole testing framework to vcr? So that I feel writing new tests will become much, much easier.

**Comment by lmazuel** [comment]
@sfdye I'm pretty sure it's possible. The only drawback I know with VCRPy, it's not thread-friendly if you want to parallelize tests (it uses mock to replace the `HTTPSRequestsConnectionClass` statically). But your current Framework has the same issue anyway, since you replace a class attribute `__httpsConnectionClass `
I try to do a proof-of-concept and link the PR here. I can't commit to any date though :/

**Comment by sfdye** [comment]
@lmazuel That will be awesome. Waiting for your PR 😝

**Comment by asottile** [comment]
Would anyone be opposed to a PR which removes the bulky data files? I could work on that

**Comment by sfdye** [comment]
Go ahead. Don't wanna be blocked by historical issues.

**Comment by sfdye** [comment]
Closed in #1031

**Comment by asottile** [comment]
This is awesome!  Thanks a ton for this @sfdye -- looking forward to the release :D

**Comment by sfdye** [comment]
![image](https://user-images.githubusercontent.com/1016390/56181024-56158300-603e-11e9-967f-950b636dca51.png)

`1.43.7` out now :)

**Comment by ChaiBapchya** [comment]
tests were removed from the tarball under the assumption that example/documentation of how to use it will be provided.
A is done but B hasn't.
